config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  resources :boards, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  include ActionView::RecordIdentifier

  validates :name, presence: true
  validates :email, presence: true, length: {maximum: 254}, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :height, numericality: { only_integer: true, greater_than: 0 }
  validates :width, numericality: { only_integer: true, greater_than: 0 }
  validates :mine_count, numericality: { only_integer: true, greater_than: 0 }
  validate :mine_count_is_less_than_board_size

  after_create_commit :generate_layout

  after_update_commit -> { broadcast_name_change }

  scope :latest_ten, -> { order(created_at: :desc).limit(10) }

  def broadcast_name_change
    broadcast_update_to(self, target: dom_id(self), renderable: BoardRowComponent.with_collection(self.layout))
  end

  private 

  def generate_layout
    GenerateLayoutJob.perform_later(board_id: id)
  end

  def mine_count_is_less_than_board_size
    if mine_count && height && width
      if mine_count > height * width 
        errors.add(:mine_count, "should be less than height * width of board")
      end
    end
  end
end

app/models/board_generator.rb
class BoardGenerator
  def self.call(height:, width:, mine_count: 0)
    tiles = Array.new(height * width - mine_count, Tile.new(mine: false, revealed: false, flagged: false))
    tiles += Array.new(mine_count, Tile.new(mine: true, revealed: false, flagged: false))
    tiles.shuffle.each_slice(width).to_a
  end
end

app/models/tile.rb
class Tile
  attr_reader :mine, :revealed, :flagged

  def initialize(mine: false, revealed: false, flagged: false)
    @mine = mine
    @revealed = revealed
    @flagged = flagged
  end

  def mine?
    @mine
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(permitted_params)
    if @board.save
      redirect_to board_path(@board)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:board).permit(:width, :height, :mine_count, :email, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @boards = Board.latest_ten
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<div class="container container-sm">
  <%= link_to "Home", root_path %>
  <div class="board__title">
    <h1>Mine Sweeper Board Generator </h1>
  </div>
  <div class="board__header">
    <h3>All Boards</h3>
    <%= link_to "Create New Board", new_board_path %>
  </div>
    
  <div>
    <ul class="board__list">
      <%= render BoardListItemComponent.with_collection(Board.latest_ten) %>
    </ul>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
  <%= link_to "Home", root_path %>
  <% if @board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>
      <ul>
        <% @board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @board do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "John Doe" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "john.doe@example.com" %>
      </div>

      <div class="form-group">
        <%= f.label :height %>
        <%= f.number_field :height, placeholder: 5 %>
      </div>

      <div class="form-group">
        <%= f.label :width %>
        <%= f.number_field :width, placeholder: 5 %>
      </div>

      <div class="form-group">
        <%= f.label :mine_count %>
        <%= f.number_field :mine_count, placeholder: 5 %>
      </div>

      <div class="form-group">
        <%= f.submit "Generate Board", class: 'submit-button' %>
      </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="container">
  <%= render BoardComponent.new(board: @board) %>
</div>

app/views/home/index.html.erb
<div class="container container-sm">
  <div class="board__title">
    <h1>Mine Sweeper Board Generator </h1>
  </div>
  <div class="board__header">
    <h3>Recent Boards</h3>
    <%= link_to "Create New Board", new_board_path %>
  </div>
    
  <div>
    <ul class="board__list">
      <%= render BoardListItemComponent.with_collection(@boards) %>
    </ul>
  </div>
  <div class="centered-link">
    <%= link_to "View all generated boards", boards_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mswobw</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/be54181fa6.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>